// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TequioDemoTrack.Data;

#nullable disable

namespace TequioDemoTrack.Migrations
{
    [DbContext(typeof(TequioDemoTrackDbContext))]
    [Migration("20250123183946_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1bf76715-faa1-440f-8b6f-bdd1bdf1b55f",
                            Email = "admina@strator.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEH9hF/GiYHtuVCqSE8ZnXF19z7s7AlWCrnkzdY7tHLW/v0BtlIWku6JM94ISAwPIWg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "89183072-0c98-4b35-b23c-cef47f73dd1a",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "d7f5e876-91fe-4e0b-a2c9-e6a07500f50e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95fcd0f0-aa36-4d66-bccf-05624986f339",
                            Email = "jordan@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMSoh4PRmeXxAaaFwd9jw9C51btce0z/OmUpzOvKDUlHO9YHuQv/by8p6te1EyS3lA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9249f3d1-1bca-42bd-81f7-aafa501a1617",
                            TwoFactorEnabled = false,
                            UserName = "SmithJordan"
                        },
                        new
                        {
                            Id = "f7b45b7d-3c74-4dfd-a8f9-20fe7b8cb062",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "16c0a99b-9f4e-4bb7-8f16-a958663b2786",
                            Email = "taylor@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEM0RcbH72P6K2LI5rW7nZC2Hns6/+blFVuS9XQeJomXcwrIzsZn3w8Ou3VHXEgR/eg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ac74f04e-ab4a-48fd-8813-793e6dd1da8f",
                            TwoFactorEnabled = false,
                            UserName = "JohnsonTaylor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TequioDemoTrack.Models.AgeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AgeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Group = "18-24"
                        },
                        new
                        {
                            Id = 2,
                            Group = "25-34"
                        },
                        new
                        {
                            Id = 3,
                            Group = "35-44"
                        },
                        new
                        {
                            Id = 4,
                            Group = "45-54"
                        },
                        new
                        {
                            Id = 5,
                            Group = "55-64"
                        },
                        new
                        {
                            Id = 6,
                            Group = "65-74"
                        });
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AgeGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgeGroupId");

                    b.HasIndex("GenderId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RaceId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Downtown LA",
                            AgeGroupId = 1,
                            Email = "john.doe@example.com",
                            GenderId = 1,
                            LocationId = 1,
                            Name = "John Doe",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St, Hollywood",
                            AgeGroupId = 2,
                            Email = "jane.smith@example.com",
                            GenderId = 2,
                            LocationId = 2,
                            Name = "Jane Smith",
                            RaceId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak St, Beverly Hills",
                            AgeGroupId = 3,
                            Email = "mark.brown@example.com",
                            GenderId = 1,
                            LocationId = 3,
                            Name = "Mark Brown",
                            RaceId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "111 Maple Ave, Santa Monica",
                            AgeGroupId = 4,
                            Email = "emily.davis@example.com",
                            GenderId = 2,
                            LocationId = 4,
                            Name = "Emily Davis",
                            RaceId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "222 Pine St, Venice",
                            AgeGroupId = 5,
                            Email = "michael.wilson@example.com",
                            GenderId = 3,
                            LocationId = 5,
                            Name = "Michael Wilson",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "333 Cedar Rd, Pasadena",
                            AgeGroupId = 6,
                            Email = "sarah.johnson@example.com",
                            GenderId = 2,
                            LocationId = 6,
                            Name = "Sarah Johnson",
                            RaceId = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "444 Birch Ln, Westwood",
                            AgeGroupId = 1,
                            Email = "david.lee@example.com",
                            GenderId = 3,
                            LocationId = 7,
                            Name = "David Lee",
                            RaceId = 3
                        },
                        new
                        {
                            Id = 8,
                            Address = "555 Willow Dr, Silver Lake",
                            AgeGroupId = 2,
                            Email = "jessica.white@example.com",
                            GenderId = 1,
                            LocationId = 8,
                            Name = "Jessica White",
                            RaceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Address = "666 Vine St, Echo Park",
                            AgeGroupId = 3,
                            Email = "james.miller@example.com",
                            GenderId = 3,
                            LocationId = 9,
                            Name = "James Miller",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 10,
                            Address = "777 Redwood St, Culver City",
                            AgeGroupId = 4,
                            Email = "laura.moore@example.com",
                            GenderId = 2,
                            LocationId = 10,
                            Name = "Laura Moore",
                            RaceId = 2
                        },
                        new
                        {
                            Id = 11,
                            Address = "888 Laurel St, Downtown LA",
                            AgeGroupId = 5,
                            Email = "robert.clark@example.com",
                            GenderId = 1,
                            LocationId = 1,
                            Name = "Robert Clark",
                            RaceId = 3
                        },
                        new
                        {
                            Id = 12,
                            Address = "999 Cherry Ave, Hollywood",
                            AgeGroupId = 6,
                            Email = "linda.martinez@example.com",
                            GenderId = 2,
                            LocationId = 2,
                            Name = "Linda Martinez",
                            RaceId = 4
                        },
                        new
                        {
                            Id = 13,
                            Address = "123 Cypress Ln, Beverly Hills",
                            AgeGroupId = 1,
                            Email = "charles.garcia@example.com",
                            GenderId = 3,
                            LocationId = 3,
                            Name = "Charles Garcia",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 14,
                            Address = "456 Magnolia Blvd, Santa Monica",
                            AgeGroupId = 2,
                            Email = "sophia.rodriguez@example.com",
                            GenderId = 1,
                            LocationId = 4,
                            Name = "Sophia Rodriguez",
                            RaceId = 2
                        },
                        new
                        {
                            Id = 15,
                            Address = "789 Dogwood St, Venice",
                            AgeGroupId = 3,
                            Email = "daniel.hall@example.com",
                            GenderId = 3,
                            LocationId = 5,
                            Name = "Daniel Hall",
                            RaceId = 3
                        },
                        new
                        {
                            Id = 16,
                            Address = "111 Fir St, Pasadena",
                            AgeGroupId = 4,
                            Email = "olivia.lopez@example.com",
                            GenderId = 2,
                            LocationId = 6,
                            Name = "Olivia Lopez",
                            RaceId = 4
                        },
                        new
                        {
                            Id = 17,
                            Address = "222 Ash St, Westwood",
                            AgeGroupId = 5,
                            Email = "paul.hernandez@example.com",
                            GenderId = 1,
                            LocationId = 7,
                            Name = "Paul Hernandez",
                            RaceId = 1
                        },
                        new
                        {
                            Id = 18,
                            Address = "333 Palm Ave, Silver Lake",
                            AgeGroupId = 6,
                            Email = "anna.king@example.com",
                            GenderId = 2,
                            LocationId = 8,
                            Name = "Anna King",
                            RaceId = 2
                        },
                        new
                        {
                            Id = 19,
                            Address = "444 Fir Ln, Echo Park",
                            AgeGroupId = 1,
                            Email = "steven.wright@example.com",
                            GenderId = 3,
                            LocationId = 9,
                            Name = "Steven Wright",
                            RaceId = 3
                        },
                        new
                        {
                            Id = 20,
                            Address = "555 Oak Blvd, Culver City",
                            AgeGroupId = 2,
                            Email = "megan.scott@example.com",
                            GenderId = 1,
                            LocationId = 10,
                            Name = "Megan Scott",
                            RaceId = 4
                        });
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GenderValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenderValue = "Male"
                        },
                        new
                        {
                            Id = 2,
                            GenderValue = "Female"
                        },
                        new
                        {
                            Id = 3,
                            GenderValue = "Non-binary"
                        });
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationValue = "Downtown LA"
                        },
                        new
                        {
                            Id = 2,
                            LocationValue = "Hollywood"
                        },
                        new
                        {
                            Id = 3,
                            LocationValue = "Beverly Hills"
                        },
                        new
                        {
                            Id = 4,
                            LocationValue = "Santa Monica"
                        },
                        new
                        {
                            Id = 5,
                            LocationValue = "Venice"
                        },
                        new
                        {
                            Id = 6,
                            LocationValue = "Pasadena"
                        },
                        new
                        {
                            Id = 7,
                            LocationValue = "Westwood"
                        },
                        new
                        {
                            Id = 8,
                            LocationValue = "Silver Lake"
                        },
                        new
                        {
                            Id = 9,
                            LocationValue = "Echo Park"
                        },
                        new
                        {
                            Id = 10,
                            LocationValue = "Culver City"
                        });
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pack")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "/Blanco.png",
                            Ingredients = "El Mexicano® Tequila Blanco (Certified Additive-Free, 100% De Agave), Sparkling Water, Natural Lime Flavor, Citric Acid",
                            Name = "Sparkling Blanco",
                            Pack = 8,
                            Price = 39.98m
                        },
                        new
                        {
                            Id = 2,
                            Image = "/Blanco.png",
                            Ingredients = "El Mexicano® Tequila Blanco (Certified Additive-Free, 100% De Agave), Sparkling Water, Natural Lime Flavor, Citric Acid",
                            Name = "Sparkling Blanco",
                            Pack = 24,
                            Price = 119.94m
                        },
                        new
                        {
                            Id = 3,
                            Image = "/Repasado.png",
                            Ingredients = "El Mexicano® Tequila Repasado (Certified Additive-Free, 100% De Agave), Sparkling Water, Natural Lime Flavor, Citric Acid",
                            Name = "Sparkling Repasado",
                            Pack = 8,
                            Price = 39.98m
                        },
                        new
                        {
                            Id = 4,
                            Image = "/Repasado.png",
                            Ingredients = "El Mexicano® Tequila Repasado (Certified Additive-Free, 100% De Agave), Sparkling Water, Natural Lime Flavor, Citric Acid",
                            Name = "Sparkling Repasado",
                            Pack = 24,
                            Price = 119.94m
                        });
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 3,
                            PurchaseDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 5,
                            PurchaseDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 7,
                            PurchaseDate = new DateTime(2023, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 9,
                            PurchaseDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2023, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 4,
                            PurchaseDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 6,
                            PurchaseDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 8,
                            PurchaseDate = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 10,
                            PurchaseDate = new DateTime(2023, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 3,
                            PurchaseDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 5,
                            PurchaseDate = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 7,
                            PurchaseDate = new DateTime(2024, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 9,
                            PurchaseDate = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 4,
                            PurchaseDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 6,
                            PurchaseDate = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 8,
                            PurchaseDate = new DateTime(2024, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 10,
                            PurchaseDate = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 21,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 22,
                            CustomerId = 3,
                            PurchaseDate = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 23,
                            CustomerId = 5,
                            PurchaseDate = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 24,
                            CustomerId = 7,
                            PurchaseDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 25,
                            CustomerId = 9,
                            PurchaseDate = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 26,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 27,
                            CustomerId = 4,
                            PurchaseDate = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 28,
                            CustomerId = 6,
                            PurchaseDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 29,
                            CustomerId = 8,
                            PurchaseDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 3
                        },
                        new
                        {
                            Id = 30,
                            CustomerId = 10,
                            PurchaseDate = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserProfileId = 2
                        });
                });

            modelBuilder.Entity("TequioDemoTrack.Models.PurchaseProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            PurchaseId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 3,
                            PurchaseId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            PurchaseId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 1,
                            PurchaseId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            PurchaseId = 3,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 2,
                            PurchaseId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 1,
                            PurchaseId = 4,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 2,
                            PurchaseId = 4,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 3,
                            PurchaseId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 1,
                            PurchaseId = 5,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 2,
                            PurchaseId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 3,
                            PurchaseId = 6,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 1,
                            PurchaseId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 2,
                            PurchaseId = 7,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 3,
                            PurchaseId = 8,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 1,
                            PurchaseId = 8,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 2,
                            PurchaseId = 9,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 3,
                            PurchaseId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 1,
                            PurchaseId = 10,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 2,
                            PurchaseId = 10,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 3,
                            PurchaseId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 2,
                            PurchaseId = 11,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 1,
                            PurchaseId = 12,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 3,
                            PurchaseId = 12,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 2,
                            PurchaseId = 13,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 1,
                            PurchaseId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 3,
                            PurchaseId = 14,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 2,
                            PurchaseId = 14,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 1,
                            PurchaseId = 15,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 3,
                            PurchaseId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 2,
                            PurchaseId = 16,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 1,
                            PurchaseId = 16,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 3,
                            PurchaseId = 17,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 2,
                            PurchaseId = 17,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 1,
                            PurchaseId = 18,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 3,
                            PurchaseId = 18,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 2,
                            PurchaseId = 19,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 1,
                            PurchaseId = 19,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 3,
                            PurchaseId = 20,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 2,
                            PurchaseId = 20,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 1,
                            PurchaseId = 21,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 3,
                            PurchaseId = 21,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 2,
                            PurchaseId = 22,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 1,
                            PurchaseId = 22,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 3,
                            PurchaseId = 23,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 2,
                            PurchaseId = 23,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 1,
                            PurchaseId = 24,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 3,
                            PurchaseId = 24,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 2,
                            PurchaseId = 25,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 1,
                            PurchaseId = 25,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 3,
                            PurchaseId = 26,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 2,
                            PurchaseId = 26,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 1,
                            PurchaseId = 27,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 3,
                            PurchaseId = 27,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 2,
                            PurchaseId = 28,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 1,
                            PurchaseId = 28,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 3,
                            PurchaseId = 29,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 2,
                            PurchaseId = 29,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 1,
                            PurchaseId = 30,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 3,
                            PurchaseId = 30,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RaceValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RaceValue = "Asian"
                        },
                        new
                        {
                            Id = 2,
                            RaceValue = "Black"
                        },
                        new
                        {
                            Id = 3,
                            RaceValue = "White"
                        },
                        new
                        {
                            Id = 4,
                            RaceValue = "Hispanic"
                        });
                });

            modelBuilder.Entity("TequioDemoTrack.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Main Street",
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            IsActive = false,
                            LastName = "Strator",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "202 Oak Avenue",
                            FirstName = "Jordan",
                            IdentityUserId = "d7f5e876-91fe-4e0b-a2c9-e6a07500f50e",
                            IsActive = false,
                            LastName = "Smith",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "303 Pine Street",
                            FirstName = "Taylor",
                            IdentityUserId = "f7b45b7d-3c74-4dfd-a8f9-20fe7b8cb062",
                            IsActive = false,
                            LastName = "Johnson",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Customer", b =>
                {
                    b.HasOne("TequioDemoTrack.Models.AgeGroup", "AgeGroup")
                        .WithMany("Customers")
                        .HasForeignKey("AgeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequioDemoTrack.Models.Gender", "Gender")
                        .WithMany("Customers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequioDemoTrack.Models.Location", "Location")
                        .WithMany("Customers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequioDemoTrack.Models.Race", "Race")
                        .WithMany("Customers")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgeGroup");

                    b.Navigation("Gender");

                    b.Navigation("Location");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Purchase", b =>
                {
                    b.HasOne("TequioDemoTrack.Models.Customer", "Customer")
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequioDemoTrack.Models.UserProfile", "UserProfile")
                        .WithMany("Purchases")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.PurchaseProduct", b =>
                {
                    b.HasOne("TequioDemoTrack.Models.Product", "Product")
                        .WithMany("PurchaseProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequioDemoTrack.Models.Purchase", "Purchase")
                        .WithMany("PurchaseProducts")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.AgeGroup", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Customer", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Gender", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Location", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Product", b =>
                {
                    b.Navigation("PurchaseProducts");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseProducts");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.Race", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("TequioDemoTrack.Models.UserProfile", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
